### ISSUE TITLE
[FEATURE] TODO: Add comments for things normal people can understand

### ISSUE THREAD

**Issue by SoupDevHub** [sandwich-machine/sandwich-machine#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Information

I'm stupid and need more comments so I understand things (pls respond to my DM electron).

### How will this improve our application

The "Main Developer" will be able to develop.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by electron271** [comment]
Already added
