### ISSUE TITLE
[BUG] Window closes when it really shouldn't

### ISSUE THREAD

**Issue by SoupDevHub** [sandwich-machine/sandwich-machine#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you select option 1 the window closes immediately.

### Expected Behavior

I expected that it worked.

### Steps To Reproduce

1. run the program
2. press 1
3. press enter

### Environment

```markdown
- OS: Windows
- Python: 3.9.6
- pip3: 21.1.3
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by electron271** [comment]
Hi, I am currently trying to replicate the issue, I will update this issue with the results soon.

**Comment by electron271** [comment]
I tried on python 3.10, it works.

**Comment by electron271** [comment]
Try updating your python, if that doesnt work, I'll reopen this issue

**Comment by SoupDevHub** [comment]
i forgot if this is still a thing

**Comment by electron271** [comment]
I don't know.. I don't have python atm so I can't test..

**Comment by SoupDevHub** [comment]
its fixed
