### ISSUE TITLE
[FEATURE] Diets

### ISSUE THREAD

**Issue by SoupDevHub** [sandwich-machine/sandwich-machine#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Information

Select if you are on a specific diet and give you a set of options if you are, also have an option to open an issue to request a new diet. 

### How will this improve our application

As a pescatarian I would use this feature, you can just run it over and over but this is a little easier.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by electron271** [comment]
@SoupDevHub Please specify some examples, I will try to work on it ASAP.

**Comment by SoupDevHub** [comment]
@electron271 pescatarian, vegetarian, vegan, keto, low fat, low carb, etc.

**Comment by electron271** [comment]
Vegetarian and vegan will make it in for now, the others might be added eventually.
