### ISSUE TITLE
[FEATURE] Shell version of run.bat

### ISSUE THREAD

**Issue by SoupHuman** [sandwich-machine/sandwich-machine#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Information

I know nothing about shell so help is needed

### How will this improve our application

you cant use batch on anything except windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by electron271** [comment]
Try adding this
File name: run (NO FILE EXTENSION)
```bash
#!/bin/bash
py main.py
```

**Comment by SoupHuman** [comment]
this shouldve been closed a long time ago
