### ISSUE TITLE
[BUG] Crashes when you try to generate a sandwich in cmd line.

### ISSUE THREAD

**Issue by SoupHuman** [sandwich-machine/sandwich-machine#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Crashes when you try to generate a sandwich and creates a blank file if you tell it to create one.

### Expected Behavior

# I would've expected it to work.

### Steps To Reproduce

1. Run the file.
2. Try to generate a sandwich in any way.

### Environment

```markdown
- OS: Windows 10 21H2
- Python: 3.9.6
- pip3: 21.1.3
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SoupHuman** [comment]
Sorta fixed

**Comment by SoupHuman** [comment]
im gonna try re merging diets soon

**Comment by SoupHuman** [comment]
output to file works but generating in cmd doesnt

**Comment by electron271** [comment]
Any updates?
