### ISSUE TITLE
[Core] Port to javascript

### ISSUE THREAD

**Issue by electron271** [sandwich-machine/sandwich-machine#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Information

Move the code to Node.js (Maybe typescript instead)

### How will this improve our application

This will add the improvements of javascript/typescript and with electron we can add a GUI!

### Agreements

- [X] I agree to follow this project's Code of Conduct

**Comment by SoupHuman** [comment]
this should be a different repo

**Comment by electron271** [comment]
Superseded by #28
