### ISSUE TITLE
[BUG] Recipes are objectively false.

### ISSUE THREAD

**Issue by SoupHuman** [sandwich-machine/sandwich-machine#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Recipes don't specify triangles when cutting sandwiches.

### Expected Behavior

I expected it to WORK!

### Steps To Reproduce

Make a sandwich, see the chaos.

### Environment

```markdown
- OS:
- Python:
- pip3:
```

### Anything else?

![image](https://user-images.githubusercontent.com/77903666/184982563-b49a27d4-3900-476c-9aa0-52848b41879e.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by electron271** [comment]
some people like to cut sandwiches the wrong way, but i'll look at this in detail asap
