### ISSUE TITLE
[CORE] bug issue template still shows python environment

### ISSUE THREAD

**Issue by SoupHuman** [sandwich-machine/sandwich-machine#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Information

self explanitory

### How will this improve our application

we've ported to js already

### Agreements

- [X] I agree to follow this project's Code of Conduct

**Comment by electron271** [comment]
oh yeah, sorry about that, i'll be right on it!

**Comment by electron271** [comment]
oh wait you already did it
