### ISSUE TITLE
[BUG] Opens, but doesn't generate sandwich when run through run.bat.

### ISSUE THREAD

**Issue by SoupHuman** [sandwich-machine/sandwich-machine#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Opens, but doesn't generate sandwich when run through run.bat.

### Expected Behavior

Opens, and generates sandwich when run through run.bat.

### Steps To Reproduce

Try to generate a sandwich.

### Environment

```markdown
- OS: Windows 10 Pro 21H2
- Node: 16.16.0
- npm: 8.11.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by electron271** [comment]
Hey, I can help more tomorrow, but just asking if you got any errors? Run it from your shell, and if you can use the `-v` flag for extra info or a debug mode if you can. I wouldn't recommend using the shell files, these will be removed as soon as we package sandwich machine.

**Comment by electron271** [comment]
@SoupHuman Update, if you can I would recommend using a debugger tool, I think you use VS Code, that one has a nice debug utility.

**Comment by SoupHuman** [comment]
run.bat was deleted
